FROM python:3.10-bullseye

# Install Rust compiler
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY ./model/cira-classifier.bin model/cira-classifier.bin
COPY ./model/cira-labeler.ckpt model/cira-labeler.ckpt

ENV MODEL_CLASSIFICATION_DEV=/app/model/cira-classifier.bin
ENV MODEL_LABELING_DEV=/app/model/cira-labeler.ckpt

# Required for Jupyter
RUN pip3 install ipykernel

# Install Python dependencies
COPY requirements.txt .
RUN pip3 install -r requirements.txt

